name: release

on:
  workflow_dispatch:

jobs:
    release:
      name: Release
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            version: "0.6.14"

        - name: "Set up Python"
          uses: actions/setup-python@v5
          with:
            python-version-file: ".python-version"

        - name: Build
          run: uv build
        
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: release
            path: dist/
