name: release

on:
  workflow_dispatch:

jobs:
    release:
      name: Release
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5

        - name: Install our dev tools
          run: uv sync --all-extras --dev

        - name: Build the project
          run: uv build
